language: minimal
services: docker

branches:
    only:
        - master
        - /^release-[0-9]+\..*$/

before_script:
    - make init

jobs:
    include:
        - stage: build test push
          script:
              - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export COMPONENT_TAG_EXTENSION="-PR${TRAVIS_PULL_REQUEST}-${TRAVIS_COMMIT}"; fi;
              - make component/build
              - if [ "$DOCKER_PASS" != "" ]; then make component/push ; else echo "No DOCKER_PASS. Skipping image push."; fi

        - stage: fast forward commits to release branch
          if: type = push AND branch =~ /^master$/
          script: make release-ff

        - stage: update release manifest
          if: type = push AND branch =~ /^release-[0-9]+\..*$/
          script: make pipeline-manifest/update PIPELINE_MANIFEST_COMPONENT_SHA256=${TRAVIS_COMMIT} PIPELINE_MANIFEST_COMPONENT_REPO=${TRAVIS_REPO_SLUG} PIPELINE_MANIFEST_BRANCH=${TRAVIS_BRANCH}
