# Copyright Contributors to the Open Cluster Management project


apiVersion: config.openshift.io/v1
kind: FeatureGate
metadata:
  name: open-cluster-management-discovery
  labels:
    open-cluster-management: ''
spec:
  featureSet: DiscoveryEnabled